#!/usr/bin/env bash
set -e

# Parse args
BUILD_TYPE="Debug"

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -d) BUILD_TYPE="Debug" ;;
        -r) BUILD_TYPE="Release" ;;
    esac
    shift
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

BUILD_STATE_FILE="$ROOT/build_number.txt"
VERSION_HEADER="$ROOT/SF_Engine/Engine/Version.cpp"

CURRENT_YEAR=$(date +%Y)
CURRENT_MONTH_PADDED=$(date +%m)          # "08", display-only
CURRENT_MONTH=$((10#$CURRENT_MONTH_PADDED))  # force base-10: bash treats 08/09 as invalid octal otherwise

if [[ -f "$BUILD_STATE_FILE" ]]; then
    STATE_BUILD=$(grep -o '[0-9]*' "$BUILD_STATE_FILE")

    BUILD_NUMBER=$((STATE_BUILD + 1))
fi

mkdir -p "$(dirname "$BUILD_STATE_FILE")"
cat > "$BUILD_STATE_FILE" <<EOF
$BUILD_NUMBER
EOF

echo "==> Version: $CURRENT_YEAR.$CURRENT_MONTH_PADDED.$BUILD_NUMBER"

# Generate Version.cpp
mkdir -p "$(dirname "$VERSION_HEADER")"
cat > "$VERSION_HEADER" <<EOF
// Auto-generated by build
#include "Version.hpp"

namespace SF::Engine {
const uint16_t Engine_VERSION_MAJOR = $CURRENT_YEAR;
const uint8_t Engine_VERSION_MINOR = $CURRENT_MONTH;
const uint16_t Engine_VERSION_PATCH = $BUILD_NUMBER;
const std::string_view Engine_VERSION = "$CURRENT_YEAR.$CURRENT_MONTH_PADDED.$BUILD_NUMBER";
} // namespace SF::Engine
EOF

echo "==> Building $BUILD_TYPE ..."

BUILD_DIR="$ROOT/build/$BUILD_TYPE"

if [[ ! -f "$BUILD_DIR/CMakeCache.txt" ]]; then
    echo "Error: not a CMake build directory: $BUILD_DIR"
    echo "Run CMake configure first."
    exit 1
fi

cmake --build "$BUILD_DIR" --config "$BUILD_TYPE"

echo "==> Build succeeded"