// Auto-generated by build
#pragma once

#include <cstdint>
#include <string_view>

namespace SF::Engine {
constexpr uint16_t Engine_VERSION_MAJOR = 2026;
constexpr uint8_t Engine_VERSION_MINOR = 8;
constexpr uint16_t Engine_VERSION_PATCH = 491;
constexpr std::string_view Engine_VERSION = "2026.08.491";
} // namespace SF::Engine
