// Auto-generated by build
#include "Version.hpp"

namespace SF::Engine {
const uint16_t Engine_VERSION_MAJOR = 2026;
const uint8_t Engine_VERSION_MINOR = 8;
const uint16_t Engine_VERSION_PATCH = 568;
const std::string_view Engine_VERSION = "2026.08.568";
} // namespace SF::Engine
