// Auto-generated by CMake
#pragma once

#include <cstdint>
#include <string_view>

namespace SF::Engine {
constexpr uint16_t Engine_VERSION_MAJOR =  2026;
constexpr uint8_t Engine_VERSION_MINOR = 06;
constexpr uint16_t Engine_VERSION_PATCH = 72;
constexpr std::string_view Engine_VERSION = "2026.06.72";
} // namespace SF::Engine
