# build.ps1 : recompile (does NOT re-run conan or cmake configure)
# Also generates Version.cpp and manages a monthly-resetting build number.
# Usage: ./scripts/build.ps1

param(
    [switch]$d,
    [switch]$r
)

$buildType = "debug"
if ($r) { $buildType = "release" }

$out = "$PSScriptRoot/../000-Build-$buildType-x64"

$root = Split-Path $PSScriptRoot -Parent
Push-Location $root

$buildStateFile = Join-Path $root "build\.build_state.json"
$versionHeader = Join-Path $root "SF_Engine\Engine\Version.cpp"

$now = Get-Date
$currentYear = $now.Year
$currentMonth = $now.Month          # int, e.g. 8, never a padded string, so no octal risk downstream
$currentMonthPadded = $now.ToString("MM")   # "08", display-only, never fed back into a numeric literal

$buildNumber = 1
if (Test-Path $buildStateFile) {
    try {
        $state = Get-Content $buildStateFile -Raw | ConvertFrom-Json
        if ($state.year -eq $currentYear -and $state.month -eq $currentMonth) {
            $buildNumber = [int]$state.buildNumber + 1
        }
        # else: different month (or corrupt/missing fields) -> stays at 1, fresh month
    }
    catch {
        Write-Host "Warning: build state file unreadable, resetting build number" -ForegroundColor Yellow
    }
}

$newState = @{
    year        = $currentYear
    month       = $currentMonth
    buildNumber = $buildNumber
}
$stateDir = Split-Path $buildStateFile -Parent
if (-not (Test-Path $stateDir)) { New-Item -ItemType Directory -Path $stateDir -Force | Out-Null }
$newState | ConvertTo-Json | Set-Content $buildStateFile

Write-Host "==> Version: $currentYear.$currentMonthPadded.$buildNumber" -ForegroundColor Cyan

# Generate Version.cpp
# Numeric fields use plain decimal ints (no leading zero -> no C++ octal-literal bug).
# The display string uses the zero-padded month for readability.
$versionHeaderContent = @"
// Auto-generated by build
#include "Version.hpp"

namespace SF::Engine {
const uint16_t Engine_VERSION_MAJOR = $currentYear;
const uint8_t Engine_VERSION_MINOR = $currentMonth;
const uint16_t Engine_VERSION_PATCH = $buildNumber;
const std::string_view Engine_VERSION = "$currentYear.$currentMonthPadded.$buildNumber";
} // namespace SF::Engine
"@

$versionHeaderDir = Split-Path $versionHeader -Parent
if (-not (Test-Path $versionHeaderDir)) { New-Item -ItemType Directory -Path $versionHeaderDir -Force | Out-Null }
Set-Content -Path $versionHeader -Value $versionHeaderContent -NoNewline


function Import-VsDevEnvironment {
    if ($env:VSCMD_ARG_TGT_ARCH) { return } # already in a dev shell, don't redo it

    $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
    if (-not (Test-Path $vswhere)) {
        Write-Host "vswhere.exe not found -- can't locate VS install" -ForegroundColor Red
        exit 1
    }

    $vsPath = & $vswhere -latest -products * `
        -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
        -property installationPath

    if (-not $vsPath) {
        Write-Host "No VS install with C++ build tools found" -ForegroundColor Red
        exit 1
    }

    $vcvars = Join-Path $vsPath "VC\Auxiliary\Build\vcvars64.bat"
    if (-not (Test-Path $vcvars)) {
        Write-Host "vcvars64.bat not found at: $vcvars" -ForegroundColor Red
        exit 1
    }

    Write-Host "==> Activating MSVC environment ($vsPath)" -ForegroundColor DarkCyan

    # Run vcvars64.bat in cmd, dump the resulting env, import it into this process
    $envDump = cmd /c "`"$vcvars`" && set"
    foreach ($line in $envDump) {
        if ($line -match '^([^=]+)=(.*)$') {
            Set-Item -Path "Env:\$($matches[1])" -Value $matches[2]
        }
    }
}

Import-VsDevEnvironment

cmake --build --preset conan2-$buildType
if ($LASTEXITCODE -ne 0) { Write-Host "Build failed" -ForegroundColor Red; Pop-Location; exit 1 }

Write-Host "==> Build succeeded" -ForegroundColor Green
Pop-Location