# build.ps1 : recompile (does NOT re-run conan or cmake configure)
# Also generates Version.hpp and manages a monthly-resetting build number.
# Usage: ./scripts/build.ps1

param(
    [switch]$d,
    [switch]$r
)

$buildType = "debug"
if ($r) { $buildType = "release" }

$root = Split-Path $PSScriptRoot -Parent
Push-Location $root

$buildStateFile = Join-Path $root "build\.build_state.json"
$versionHeader = Join-Path $root "SF_Engine\Engine\Version.hpp"

$now = Get-Date
$currentYear = $now.Year
$currentMonth = $now.Month          # int, e.g. 8, never a padded string, so no octal risk downstream
$currentMonthPadded = $now.ToString("MM")   # "08", display-only, never fed back into a numeric literal

$buildNumber = 1
if (Test-Path $buildStateFile) {
    try {
        $state = Get-Content $buildStateFile -Raw | ConvertFrom-Json
        if ($state.year -eq $currentYear -and $state.month -eq $currentMonth) {
            $buildNumber = [int]$state.buildNumber + 1
        }
        # else: different month (or corrupt/missing fields) -> stays at 1, fresh month
    }
    catch {
        Write-Host "Warning: build state file unreadable, resetting build number" -ForegroundColor Yellow
    }
}

$newState = @{
    year        = $currentYear
    month       = $currentMonth
    buildNumber = $buildNumber
}
$stateDir = Split-Path $buildStateFile -Parent
if (-not (Test-Path $stateDir)) { New-Item -ItemType Directory -Path $stateDir -Force | Out-Null }
$newState | ConvertTo-Json | Set-Content $buildStateFile

Write-Host "==> Version: $currentYear.$currentMonthPadded.$buildNumber" -ForegroundColor Cyan

# Generate Version.hpp
# Numeric fields use plain decimal ints (no leading zero -> no C++ octal-literal bug).
# The display string uses the zero-padded month for readability.
$versionHeaderContent = @"
// Auto-generated by build.ps1
#pragma once

#include <cstdint>
#include <string_view>

namespace SF::Engine {
constexpr uint16_t Engine_VERSION_MAJOR = $currentYear;
constexpr uint8_t Engine_VERSION_MINOR = $currentMonth;
constexpr uint16_t Engine_VERSION_PATCH = $buildNumber;
constexpr std::string_view Engine_VERSION = "$currentYear.$currentMonthPadded.$buildNumber";
} // namespace SF::Engine
"@

$versionHeaderDir = Split-Path $versionHeader -Parent
if (-not (Test-Path $versionHeaderDir)) { New-Item -ItemType Directory -Path $versionHeaderDir -Force | Out-Null }
Set-Content -Path $versionHeader -Value $versionHeaderContent -NoNewline

# --- build ---
cmake --build --preset conan2-$buildType
if ($LASTEXITCODE -ne 0) { Write-Host "Build failed" -ForegroundColor Red; Pop-Location; exit 1 }

Write-Host "==> Build succeeded" -ForegroundColor Green
Pop-Location